<?php

return [
    /*
    |--------------------------------------------------------------------------
    | The directory where your files should be output, relative
    | to the public path.
    |--------------------------------------------------------------------------
    */
    'output_path' => 'build',

    /*
    |--------------------------------------------------------------------------
    | Names of the different files generated by Encore.
    |--------------------------------------------------------------------------
    */
    'files' => [
        'entrypoints' => 'entrypoints.json',
        'manifest'    => 'manifest.json',
    ],
];
